name: chm
channels:
  - conda-forge
dependencies:
  - jupyterlab
  - ipywidgets
  - ipykernel
  - ipympl
  - ipyleaflet
  - geopandas
  - plotly
  - h3-py
  - geodatasets
  - contextily
  - gdal
  - rasterio
  - dask
  - scikit-image
